build:
	nodes:
		php71:
			environment:
				php: 7.1
		php713:
			environment:
				php: 7.1.3
		php72:
			environment:
				php: 7.2
		php73:
			environment:
				php: 7.3
		analysis:
			project_setup:
				override: true
			tests:
				override:
					- php-scrutinizer-run

checks:
	php:
		code_rating: true
		duplication: true
